SOURCES = [
    {
        "source_id": "logirus",
        "source_name": "Logirus",
        "source_type": "news",
        "country": "RU",
        "fetch_method": "rss",
        "list_url": "https://logirus.ru/rss.xml",
        "category_default": "news",
        "enabled": True,
        "refresh_hours": 6,
    },
    {
        "source_id": "portnews",
        "source_name": "PortNews",
        "source_type": "news",
        "country": "RU",
        "fetch_method": "html",
        "list_url": "https://portnews.ru/",
        "article_selector": "article, .news-list-item, .item",
        "title_selector": "h2, h3, .title",
        "date_selector": "time, .date",
        "link_selector": "a",
        "snippet_selector": "p, .announce",
        "image_selector": "img",
        "category_default": "ports",
        "enabled": True,
        "refresh_hours": 12,
    },
    {
        "source_id": "freightwaves",
        "source_name": "FreightWaves",
        "source_type": "news",
        "country": "INT",
        "fetch_method": "rss",
        "list_url": "https://www.freightwaves.com/news/feed",
        "category_default": "analytics",
        "enabled": True,
        "refresh_hours": 12,
        "fallback_only": True,
    }
]
