SOURCES = [
    # --- RU / отраслевые медиа ---
    {
        "source_id": "logirus",
        "source_name": "Logirus",
        "source_group": "industry_media",
        "source_type": "news",
        "country": "RU",
        "language": "ru",
        "priority": 100,
        "fetch_method": "rss",
        "list_url": "https://logirus.ru/rss.xml",
        "category_default": "news",
        "enabled": True,
        "refresh_hours": 6,
    },
    {
        "source_id": "portnews",
        "source_name": "PortNews",
        "source_group": "ports_media",
        "source_type": "news",
        "country": "RU",
        "language": "ru",
        "priority": 95,
        "fetch_method": "html",
        "list_url": "https://portnews.ru/",
        "article_selector": "article, .news-list-item, .item, .post",
        "title_selector": "h2 a, h3 a, .title a, h2, h3, .title",
        "date_selector": "time, .date, .post-date",
        "link_selector": "h2 a, h3 a, .title a, a",
        "snippet_selector": "p, .announce, .excerpt",
        "image_selector": "img",
        "category_default": "ports",
        "enabled": True,
        "refresh_hours": 12,
    },
    {
        "source_id": "infranews",
        "source_name": "InfraNews",
        "source_group": "industry_media",
        "source_type": "news",
        "country": "RU",
        "language": "ru",
        "priority": 92,
        "fetch_method": "html",
        "list_url": "https://www.infranews.ru/",
        "article_selector": "article, .post, .td_module_wrap, .news-item",
        "title_selector": "h3 a, h2 a, .entry-title a, .title a, h3, h2",
        "date_selector": "time, .entry-date, .date",
        "link_selector": "h3 a, h2 a, .entry-title a, .title a, a",
        "snippet_selector": ".td-excerpt, .entry-summary, p, .excerpt",
        "image_selector": "img",
        "category_default": "analytics",
        "enabled": True,
        "refresh_hours": 12,
    },
    {
        "source_id": "seanews",
        "source_name": "SeaNews",
        "source_group": "ports_media",
        "source_type": "news",
        "country": "RU",
        "language": "ru",
        "priority": 90,
        "fetch_method": "html",
        "list_url": "https://seanews.ru/",
        "article_selector": "article, .post, .news-item, .jeg_post",
        "title_selector": "h3 a, h2 a, .entry-title a, .jeg_post_title a, h3, h2",
        "date_selector": "time, .date, .entry-date",
        "link_selector": "h3 a, h2 a, .entry-title a, .jeg_post_title a, a",
        "snippet_selector": ".jeg_post_excerpt, .entry-summary, p, .excerpt",
        "image_selector": "img",
        "category_default": "sea",
        "enabled": True,
        "refresh_hours": 12,
    },
    {
        "source_id": "rzd_partner",
        "source_name": "РЖД-Партнер",
        "source_group": "rail_media",
        "source_type": "news",
        "country": "RU",
        "language": "ru",
        "priority": 88,
        "fetch_method": "html",
        "list_url": "https://www.rzd-partner.ru/news/",
        "article_selector": "article, .news-list-item, .item, .post",
        "title_selector": "h3 a, h2 a, .title a, h3, h2",
        "date_selector": "time, .date",
        "link_selector": "h3 a, h2 a, .title a, a",
        "snippet_selector": ".announce, .excerpt, p",
        "image_selector": "img",
        "category_default": "rail",
        "enabled": True,
        "refresh_hours": 12,
    },
    {
        "source_id": "gudok",
        "source_name": "Гудок",
        "source_group": "rail_media",
        "source_type": "news",
        "country": "RU",
        "language": "ru",
        "priority": 84,
        "fetch_method": "html",
        "list_url": "https://gudok.ru/news/",
        "article_selector": "article, .news-item, .item, .post",
        "title_selector": "h3 a, h2 a, .title a, h3, h2",
        "date_selector": "time, .date",
        "link_selector": "h3 a, h2 a, .title a, a",
        "snippet_selector": ".announce, .excerpt, p",
        "image_selector": "img",
        "category_default": "rail",
        "enabled": True,
        "refresh_hours": 12,
    },

    # --- RU / официальные источники и операторы ---
    {
        "source_id": "rosmorport",
        "source_name": "Росморпорт",
        "source_group": "official",
        "source_type": "news",
        "country": "RU",
        "language": "ru",
        "priority": 82,
        "fetch_method": "html",
        "list_url": "https://www.rosmorport.ru/news/",
        "article_selector": "article, .news-item, .item, .post",
        "title_selector": "h3 a, h2 a, .title a, h3, h2",
        "date_selector": "time, .date",
        "link_selector": "h3 a, h2 a, .title a, a",
        "snippet_selector": ".announce, .excerpt, p",
        "image_selector": "img",
        "category_default": "ports",
        "enabled": True,
        "refresh_hours": 24,
    },
    {
        "source_id": "customs",
        "source_name": "ФТС России",
        "source_group": "official",
        "source_type": "news",
        "country": "RU",
        "language": "ru",
        "priority": 80,
        "fetch_method": "html",
        "list_url": "https://customs.gov.ru/press/federal",
        "article_selector": "article, .news-item, .item, .b-news__item",
        "title_selector": "h3 a, h2 a, .title a, .b-news__title a, h3, h2",
        "date_selector": "time, .date, .b-news__date",
        "link_selector": "h3 a, h2 a, .title a, .b-news__title a, a",
        "snippet_selector": ".announce, .excerpt, .b-news__text, p",
        "image_selector": "img",
        "category_default": "regulation",
        "enabled": True,
        "refresh_hours": 24,
    },
    {
        "source_id": "fesco",
        "source_name": "FESCO",
        "source_group": "operator",
        "source_type": "news",
        "country": "RU",
        "language": "ru",
        "priority": 78,
        "fetch_method": "html",
        "list_url": "https://www.fesco.ru/ru/press-center/news/",
        "article_selector": "article, .news-item, .item, .post",
        "title_selector": "h3 a, h2 a, .title a, h3, h2",
        "date_selector": "time, .date",
        "link_selector": "h3 a, h2 a, .title a, a",
        "snippet_selector": ".announce, .excerpt, p",
        "image_selector": "img",
        "category_default": "operator_news",
        "enabled": True,
        "refresh_hours": 24,
    },
    {
        "source_id": "delo",
        "source_name": "ГК Дело",
        "source_group": "operator",
        "source_type": "news",
        "country": "RU",
        "language": "ru",
        "priority": 76,
        "fetch_method": "html",
        "list_url": "https://www.delo-group.ru/press-center/news/",
        "article_selector": "article, .news-item, .item, .post",
        "title_selector": "h3 a, h2 a, .title a, h3, h2",
        "date_selector": "time, .date",
        "link_selector": "h3 a, h2 a, .title a, a",
        "snippet_selector": ".announce, .excerpt, p",
        "image_selector": "img",
        "category_default": "operator_news",
        "enabled": True,
        "refresh_hours": 24,
    },
    {
        "source_id": "global_ports",
        "source_name": "Global Ports",
        "source_group": "operator",
        "source_type": "news",
        "country": "RU",
        "language": "ru",
        "priority": 74,
        "fetch_method": "html",
        "list_url": "https://www.globalports.com/ru/press-center/news-and-media/",
        "article_selector": "article, .news-item, .item, .post",
        "title_selector": "h3 a, h2 a, .title a, h3, h2",
        "date_selector": "time, .date",
        "link_selector": "h3 a, h2 a, .title a, a",
        "snippet_selector": ".announce, .excerpt, p",
        "image_selector": "img",
        "category_default": "ports",
        "enabled": True,
        "refresh_hours": 24,
    },

    # --- INT / запасной пул ---
    {
        "source_id": "freightwaves",
        "source_name": "FreightWaves",
        "source_group": "international_media",
        "source_type": "news",
        "country": "INT",
        "language": "en",
        "priority": 40,
        "fetch_method": "rss",
        "list_url": "https://www.freightwaves.com/news/feed",
        "category_default": "analytics",
        "enabled": False,
        "refresh_hours": 12,
    },
    {
        "source_id": "splash247",
        "source_name": "Splash247",
        "source_group": "international_media",
        "source_type": "news",
        "country": "INT",
        "language": "en",
        "priority": 38,
        "fetch_method": "rss",
        "list_url": "https://splash247.com/feed/",
        "category_default": "sea",
        "enabled": False,
        "refresh_hours": 12,
    },
    {
        "source_id": "lloydslist",
        "source_name": "Lloyd's List",
        "source_group": "international_media",
        "source_type": "news",
        "country": "INT",
        "language": "en",
        "priority": 36,
        "fetch_method": "html",
        "list_url": "https://www.lloydslist.com/",
        "article_selector": "article, .card, .news-item, .post",
        "title_selector": "h3 a, h2 a, .title a, h3, h2",
        "date_selector": "time, .date",
        "link_selector": "h3 a, h2 a, .title a, a",
        "snippet_selector": ".excerpt, .summary, p",
        "image_selector": "img",
        "category_default": "sea",
        "enabled": False,
        "refresh_hours": 12,
    },
    {
        "source_id": "maersk",
        "source_name": "Maersk",
        "source_group": "carrier",
        "source_type": "news",
        "country": "INT",
        "language": "en",
        "priority": 34,
        "fetch_method": "html",
        "list_url": "https://www.maersk.com/news",
        "article_selector": "article, .news-item, .item, .post",
        "title_selector": "h3 a, h2 a, .title a, h3, h2",
        "date_selector": "time, .date",
        "link_selector": "h3 a, h2 a, .title a, a",
        "snippet_selector": ".excerpt, .summary, p",
        "image_selector": "img",
        "category_default": "operator_news",
        "enabled": False,
        "refresh_hours": 24,
    },
    {
        "source_id": "hapag",
        "source_name": "Hapag-Lloyd",
        "source_group": "carrier",
        "source_type": "news",
        "country": "INT",
        "language": "en",
        "priority": 32,
        "fetch_method": "html",
        "list_url": "https://www.hapag-lloyd.com/en/company/press/releases_and_news.html",
        "article_selector": "article, .news-item, .item, .post",
        "title_selector": "h3 a, h2 a, .title a, h3, h2",
        "date_selector": "time, .date",
        "link_selector": "h3 a, h2 a, .title a, a",
        "snippet_selector": ".excerpt, .summary, p",
        "image_selector": "img",
        "category_default": "operator_news",
        "enabled": False,
        "refresh_hours": 24,
    },
    {
        "source_id": "theloadstar",
        "source_name": "The Loadstar",
        "source_group": "international_media",
        "source_type": "news",
        "country": "INT",
        "language": "en",
        "priority": 30,
        "fetch_method": "rss",
        "list_url": "https://theloadstar.com/feed/",
        "category_default": "analytics",
        "enabled": False,
        "refresh_hours": 12,
    },

    # --- шаблоны под отдельные витрины rates / indices ---
    {
        "source_id": "rates_template",
        "source_name": "Rates Template",
        "source_group": "rates",
        "source_type": "rates",
        "country": "MIX",
        "language": "ru",
        "priority": 20,
        "fetch_method": "json",
        "list_url": "",
        "category_default": "rates",
        "enabled": False,
        "refresh_hours": 24,
        "note": "Шаблон под будущий источник ставок/API/Google Sheets."
    },
    {
        "source_id": "indices_template",
        "source_name": "Indices Template",
        "source_group": "indices",
        "source_type": "indices",
        "country": "MIX",
        "language": "ru",
        "priority": 20,
        "fetch_method": "json",
        "list_url": "",
        "category_default": "indices",
        "enabled": False,
        "refresh_hours": 24,
        "note": "Шаблон под будущий источник индексов/API/Google Sheets."
    },
]
