SOURCES = [
    {
        "source_id": "logirus",
        "source_name": "Logirus",
        "source_group": "industry_media",
        "source_type": "news",
        "country": "RU",
        "language": "ru",
        "priority": 100,
        "fetch_method": "rss",
        "list_url": "https://logirus.ru/rss.xml",
        "fallbacks": [{"fetch_method": "html", "list_url": "https://logirus.ru/news/"}],
        "category_default": "news",
        "focus_keywords": ["логист", "перевоз", "контейнер", "порт", "жд", "экспед", "склад", "транзит", "фрахт"],
        "enabled": True,
    },
    {
        "source_id": "portnews",
        "source_name": "PortNews",
        "source_group": "ports_media",
        "source_type": "news",
        "country": "RU",
        "language": "ru",
        "priority": 99,
        "fetch_method": "rss",
        "list_url": "https://portnews.ru/rss/",
        "fallbacks": [{"fetch_method": "html", "list_url": "https://portnews.ru/"}],
        "category_default": "ports",
        "focus_keywords": ["порт", "терминал", "судоход", "контейнер", "мор", "флот", "нефтепродукт", "экспорт"],
        "enabled": True,
    },
    {
        "source_id": "infranews",
        "source_name": "InfraNews",
        "source_group": "industry_media",
        "source_type": "news",
        "country": "RU",
        "language": "ru",
        "priority": 98,
        "fetch_method": "rss",
        "list_url": "https://www.infranews.ru/feed/",
        "fallbacks": [{"fetch_method": "html", "list_url": "https://www.infranews.ru/"}],
        "category_default": "analytics",
        "focus_keywords": ["логист", "порт", "контейнер", "железнодорож", "терминал", "перевоз", "фрахт", "экспорт"],
        "enabled": True,
    },
    {
        "source_id": "seanews",
        "source_name": "SeaNews",
        "source_group": "ports_media",
        "source_type": "news",
        "country": "RU",
        "language": "ru",
        "priority": 97,
        "fetch_method": "rss",
        "list_url": "https://seanews.ru/feed/",
        "fallbacks": [{"fetch_method": "html", "list_url": "https://seanews.ru/"}],
        "category_default": "sea",
        "focus_keywords": ["порт", "мор", "судоход", "контейнер", "линия", "фрахт", "терминал"],
        "enabled": True,
    },
    {
        "source_id": "rzd_partner",
        "source_name": "РЖД-Партнер",
        "source_group": "rail_media",
        "source_type": "news",
        "country": "RU",
        "language": "ru",
        "priority": 96,
        "fetch_method": "html",
        "list_url": "https://www.rzd-partner.ru/news/",
        "article_selector": "article, .news-list-item, .item, .post, .news-item",
        "title_selector": "h3 a, h2 a, .title a, h3, h2",
        "date_selector": "time, .date",
        "link_selector": "h3 a, h2 a, .title a, a[href]",
        "snippet_selector": ".announce, .excerpt, p",
        "category_default": "rail",
        "focus_keywords": ["жд", "поезд", "контейнер", "логист", "станц", "терминал", "транссиб"],
        "enabled": True,
    },
    {
        "source_id": "morvesti",
        "source_name": "Морские вести России",
        "source_group": "ports_media",
        "source_type": "news",
        "country": "RU",
        "language": "ru",
        "priority": 93,
        "fetch_method": "html",
        "list_url": "https://morvesti.ru/news/",
        "article_selector": "article, .news-item, .item, .post, .entry",
        "title_selector": "h3 a, h2 a, .title a, .entry-title a, h3, h2",
        "date_selector": "time, .date, .entry-date",
        "link_selector": "h3 a, h2 a, .title a, .entry-title a, a[href]",
        "snippet_selector": ".announce, .excerpt, .entry-summary, p",
        "category_default": "ports",
        "focus_keywords": ["порт", "мор", "терминал", "судоход", "каботаж", "контейнер", "флот"],
        "enabled": True,
    },
    {
        "source_id": "transport_russia",
        "source_name": "Транспорт России",
        "source_group": "official",
        "source_type": "news",
        "country": "RU",
        "language": "ru",
        "priority": 91,
        "fetch_method": "html",
        "list_url": "https://transportrussia.ru/",
        "article_selector": "article, .news-item, .item, .post",
        "title_selector": "h3 a, h2 a, .title a, .entry-title a, h3, h2",
        "date_selector": "time, .date, .entry-date",
        "link_selector": "h3 a, h2 a, .title a, .entry-title a, a[href]",
        "snippet_selector": ".announce, .excerpt, .entry-summary, p",
        "category_default": "market",
        "focus_keywords": ["логист", "транспорт", "порт", "контейнер", "жд", "авиа", "коридор", "перевоз"],
        "enabled": True,
    },
    {
        "source_id": "transru",
        "source_name": "Trans.ru",
        "source_group": "industry_media",
        "source_type": "news",
        "country": "RU",
        "language": "ru",
        "priority": 90,
        "fetch_method": "html",
        "list_url": "https://trans.ru/news/",
        "article_selector": "article, .news-item, .item, .post",
        "title_selector": "h3 a, h2 a, .title a, h3, h2",
        "date_selector": "time, .date",
        "link_selector": "h3 a, h2 a, .title a, a[href]",
        "snippet_selector": ".announce, .excerpt, p",
        "category_default": "news",
        "focus_keywords": ["логист", "перевоз", "экспед", "международ", "контейнер", "терминал", "склад"],
        "enabled": True,
    },
    {
        "source_id": "rosmorport",
        "source_name": "Росморпорт",
        "source_group": "official",
        "source_type": "news",
        "country": "RU",
        "language": "ru",
        "priority": 89,
        "fetch_method": "html",
        "list_url": "https://www.rosmorport.ru/press/news/",
        "article_selector": "article, .news-item, .item, .post",
        "title_selector": "h3 a, h2 a, .title a, h3, h2",
        "date_selector": "time, .date",
        "link_selector": "h3 a, h2 a, .title a, a[href]",
        "snippet_selector": ".announce, .excerpt, p",
        "category_default": "ports",
        "focus_keywords": ["порт", "терминал", "мор", "судоход", "гавань", "флот"],
        "enabled": True,
    },
    {
        "source_id": "customs",
        "source_name": "ФТС России",
        "source_group": "official",
        "source_type": "news",
        "country": "RU",
        "language": "ru",
        "priority": 88,
        "fetch_method": "html",
        "list_url": "https://customs.gov.ru/press/federal/news",
        "article_selector": "article, .news-item, .item, .b-news__item",
        "title_selector": "h3 a, h2 a, .title a, .b-news__title a, h3, h2",
        "date_selector": "time, .date, .b-news__date",
        "link_selector": "h3 a, h2 a, .title a, .b-news__title a, a[href]",
        "snippet_selector": ".announce, .excerpt, .b-news__text, p",
        "category_default": "regulation",
        "focus_keywords": ["тамож", "деклара", "вэд", "экспорт", "импорт", "контроль", "маркиров"],
        "enabled": True,
    },
    {
        "source_id": "fesco",
        "source_name": "FESCO",
        "source_group": "operator",
        "source_type": "news",
        "country": "RU",
        "language": "ru",
        "priority": 86,
        "fetch_method": "html",
        "list_url": "https://www.fesco.ru/ru/press-center/news/",
        "fallbacks": [{"fetch_method": "html", "list_url": "https://www.fesco.ru/ru/press-center/"}],
        "category_default": "operator_news",
        "focus_keywords": ["контейнер", "сервис", "линия", "терминал", "логист", "порт", "поезд"],
        "enabled": True,
    },
    {
        "source_id": "delo",
        "source_name": "ГК Дело",
        "source_group": "operator",
        "source_type": "news",
        "country": "RU",
        "language": "ru",
        "priority": 85,
        "fetch_method": "html",
        "list_url": "https://www.delo-group.ru/press-center/news/",
        "fallbacks": [{"fetch_method": "html", "list_url": "https://www.delo-group.ru/"}],
        "category_default": "operator_news",
        "focus_keywords": ["контейнер", "терминал", "порт", "логист", "мультимод", "сервис"],
        "enabled": True,
    },
    {
        "source_id": "global_ports",
        "source_name": "Global Ports",
        "source_group": "operator",
        "source_type": "news",
        "country": "RU",
        "language": "ru",
        "priority": 84,
        "fetch_method": "html",
        "list_url": "https://www.globalports.com/ru/press-center/news-and-media/",
        "fallbacks": [{"fetch_method": "html", "list_url": "https://www.globalports.com/ru/"}],
        "category_default": "ports",
        "focus_keywords": ["порт", "терминал", "контейнер", "логист", "сервис", "мор"],
        "enabled": True,
    },
    {
        "source_id": "russcon",
        "source_name": "RUSCON",
        "source_group": "operator",
        "source_type": "news",
        "country": "RU",
        "language": "ru",
        "priority": 83,
        "fetch_method": "html",
        "list_url": "https://russcon.ru/press-center/news/",
        "fallbacks": [{"fetch_method": "html", "list_url": "https://russcon.ru/"}],
        "category_default": "operator_news",
        "focus_keywords": ["логист", "экспед", "контейнер", "склад", "сервис", "доставка"],
        "enabled": True,
    },
    {
        "source_id": "transcontainer",
        "source_name": "ТрансКонтейнер",
        "source_group": "operator",
        "source_type": "news",
        "country": "RU",
        "language": "ru",
        "priority": 82,
        "fetch_method": "html",
        "list_url": "https://trcont.com/press/news/",
        "fallbacks": [{"fetch_method": "html", "list_url": "https://trcont.com/"}],
        "category_default": "rail",
        "focus_keywords": ["контейнер", "поезд", "жд", "терминал", "маршрут", "экспорт"],
        "enabled": True,
    },
    {
        "source_id": "utlc",
        "source_name": "UTLC ERA",
        "source_group": "operator",
        "source_type": "news",
        "country": "INT",
        "language": "ru",
        "priority": 80,
        "fetch_method": "html",
        "list_url": "https://utlc.com/news/",
        "category_default": "rail",
        "focus_keywords": ["контейнер", "транзит", "поезд", "жд", "коридор", "евразия"],
        "enabled": True,
    },
    {
        "source_id": "gudok",
        "source_name": "Гудок",
        "source_group": "rail_media",
        "source_type": "news",
        "country": "RU",
        "language": "ru",
        "priority": 79,
        "fetch_method": "html",
        "list_url": "https://gudok.ru/news/",
        "category_default": "rail",
        "focus_keywords": ["жд", "поезд", "погрузка", "контейнер", "логист", "транзит"],
        "enabled": True,
    },
    {
        "source_id": "alphaliner",
        "source_name": "Alphaliner",
        "source_group": "international_media",
        "source_type": "news",
        "country": "INT",
        "language": "en",
        "priority": 45,
        "fetch_method": "html",
        "list_url": "https://www.alphaliner.com/news/",
        "category_default": "sea",
        "focus_keywords": ["container", "liner", "shipping", "port", "capacity", "vessel"],
        "enabled": True,
    },
    {
        "source_id": "splash247",
        "source_name": "Splash247",
        "source_group": "international_media",
        "source_type": "news",
        "country": "INT",
        "language": "en",
        "priority": 35,
        "fetch_method": "rss",
        "list_url": "https://splash247.com/feed/",
        "category_default": "sea",
        "focus_keywords": ["shipping", "port", "container", "liner", "vessel", "freight"],
        "enabled": True,
    },
    {
        "source_id": "freightwaves",
        "source_name": "FreightWaves",
        "source_group": "international_media",
        "source_type": "news",
        "country": "INT",
        "language": "en",
        "priority": 20,
        "fetch_method": "rss",
        "list_url": "https://www.freightwaves.com/news/feed",
        "category_default": "rates",
        "focus_keywords": ["freight", "trucking", "logistics", "rail", "port", "shipping", "warehouse"],
        "enabled": False,
    },
]
